

run_to_execute: "xgboost_regressor_run"

xgboost_regressor_run:
  run_id: "xgbreg_demo_01"
  task_type: "regression"
  notebook_mode: true
  logging: "auto"

  pre_model_diagnostics:
    run: true
    export_reports: true
    export_html_report: true
    vif_threshold: 10.0
    skewness_threshold: 0.75

  paths:
    input_data: "data/input_data/salifort_50k.csv"
    train_data_path: "data/dev_data/train_data.csv"
    test_data_path: "data/dev_data/test_data.csv"
    reports_dir: "exports/reports"
    plots_dir: "exports/plots"
    model_export_dir: "models"
    metrics_log: "exports/reports/model_metrics_log.csv"
    log_dir: "logs"

  modeling:
    target_column: "left"
    pipeline_factory:
      name: "XGBRegressor"
      registered_name: "xgbreg_demo_01"
      numeric_features: ['number_project', 'average_montly_hours', 'time_spend_company', 'project_hours_interaction']
      categorical_features: ['Department', 'salary']
      params: {}
#        n_estimators: 100
#        max_depth: 5
#       learning_rate: 0.1
#        objective: "reg:squarederror"
#        random_state: 42
    feature_engineering:
      run: true
      module: "model_eval_suite.modeling.feature_engineering"
      class_name: "HREngineer"
    hyperparameter_tuning:
      run: true
      cv_folds: 5
      scoring: 'r2'
      param_grid:
        estimator__n_estimators: [50, 100, 150]
        estimator__max_depth: [3, 5, 7]
        estimator__learning_rate: [0.01, 0.1, 0.2]
        estimator__subsample: [0.8, 1.0]
        estimator__colsample_bytree: [0.8, 1.0]

  evaluation:
    run: true
    export_xlsx_summary: false
    export_html_dashboard: true
    compare_to_baseline: "linreg_demo_01"
    explainability:
      run_shap: true
      shap_sample_size: 2000
    audits:
      # Regression audit thresholds
      r_squared_min_threshold: 0.7
      rmse_max_threshold: 10000.0
      performance_regression_r2_threshold_factor: 0.95
      # Classification audit thresholds
      overfitting_threshold_factor: 1.15
      cv_std_threshold: 0.1
      performance_regression_f1_threshold_factor: 0.95
    plots:
      predicted_vs_actual: { save: true }
      residuals_plot: { save: true }
      residuals_histogram: { save: true }
      qq_plot: { save: true }
      feature_distributions: { save: true }
      permutation_importance: { save: true }
      shap_summary: { save: true }
      learning_curve: { save: true }